version: "3.9"

services:
  nextjs-dev:
    ports:
      - 3000:3000
    build:
      context: ./portfolio-client
      dockerfile: Dockerfile
    image: cloud.canister.io:5000/josemasri/portfolio-client
    container_name: portfolio-client
    depends_on:
      - server
  db:
    image: postgres:9.6.24-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    container_name: portfolio-db
    ports:
      - "5432:5432"
  server:
    image: cloud.canister.io:5000/josemasri/portfolio-server
    build:
      context: ./portfolio-server
      dockerfile: Dockerfile
    command: yarn develop
    volumes:
      - server-images:/app/public/uploads
    env_file: .env
    container_name: portfolio-server
    ports:
      - "1337:1337"
    depends_on:
      - db
volumes:
  db-data:
  server-images:
