version: "3.9"

services:
  client:
    ports:
      - 3000:3000
    build:
      context: ./portfolio-client
      dockerfile: Dockerfile.dev
    image: josemasri/porfolio-dev
    container_name: portfolio-client
    depends_on:
      - server
    volumes:
      - ./portfolio-client:/app
      - /app/node_modules
      - /app/.next
  db:
    image: postgres:9.6.24-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    container_name: portfolio-db
    ports:
      - "5432:5432"
  server:
    image: josemasri:portfolio-server
    build:
      context: ./portfolio-server
      dockerfile: Dockerfile
    command: yarn develop
    volumes:
      - ./portfolio-server:/app
      - /app/node_modules
    env_file: .env
    container_name: portfolio-server
    ports:
      - "1337:1337"
    depends_on:
      - db
volumes:
  db-data: